spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diabetic
    username: postgres
    password: Password01
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: debug

application:
  security:
    jwt:
      secretKey: 623BE118F956DB598F1778266DAFE623BE118F956DB598F1778266DAFE623BE118F956DB598F1778266DAFE
      expiration: 600800000
      refresh-token:
        expiration: 604800000 # 7 days
